<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <AssemblyName>GateRimSG1</AssemblyName>
        <RootNamespace>GateRimSG1</RootNamespace>
        <Version>0.1.18</Version>
        <AssemblyVersion>0.1.18.0</AssemblyVersion>
        <FileVersion>0.1.18.0</FileVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <OutputPath>..\..\1.6\Assemblies\</OutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <RimWorldManagedDir Condition="'$(RimWorldManagedDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed</RimWorldManagedDir>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(RimWorldManagedDir)\Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(RimWorldManagedDir)\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
